"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("reflect-metadata");
var Decorators_1 = require("./Decorators");
Object.defineProperty(exports, "get", { enumerable: true, get: function () { return Decorators_1.get; } });
Object.defineProperty(exports, "post", { enumerable: true, get: function () { return Decorators_1.post; } });
Object.defineProperty(exports, "put", { enumerable: true, get: function () { return Decorators_1.put; } });
Object.defineProperty(exports, "del", { enumerable: true, get: function () { return Decorators_1.del; } });
Object.defineProperty(exports, "patch", { enumerable: true, get: function () { return Decorators_1.patch; } });
Object.defineProperty(exports, "next", { enumerable: true, get: function () { return Decorators_1.next; } });
var loadRoute_1 = require("./loadRoute");
Object.defineProperty(exports, "loadRoute", { enumerable: true, get: function () { return loadRoute_1.loadRoute; } });
